### ISSUE TITLE
sending messages to IO from the sdk

### ISSUE THREAD

**Issue by sciabarra** [pagopa/io-sdk#15]
implement a "send" command that can send a message to io:

```
send <dest> <message>
```

**Comment by nimmichele** [comment]
usage: iosdk send [<recipient>] [<subject>] [<markdown>] [<key>]
Args:
  [<recipient>]  Message Recipient (fiscal code)
  [<subject>]    Message Subject
  [<markdown>]   Message Markdown
  [<key>]        API Key
