### ISSUE TITLE
Where are saved files stored?

### ISSUE THREAD

**Issue by cloudify** [pagopa/io-sdk#16]
I've launched the SDK, created a file and saved it but I can't find it anywhere in my file system.

I've launched the SDK with:

```
./iosdk_mac start
```

**Comment by sciabarra** [comment]
currently iosdk only launches docker images for editor and whisk,  so no files are saved.
next step is to introduce `iosdk init <folder>`  to create a new template to be modified and then `iosdk start <folder>` will allow to edit the files in the folder in your local folder. The init is actually already implemented but not yet the template.

**Comment by sciabarra** [comment]
In version 0.3 there is now the init command
