### ISSUE TITLE
Error during install running make

### ISSUE THREAD

**Issue by giux78** [pagopa/io-sdk#40]
I'm trying to install the developer setup for be able to contribute and following [DEVEL.md ](../blob/master/DEVEL.md)  
During `make` or `sudo make` command I have the error below seems a permission problem. 

5: Pulling from library/redis
Digest: sha256:157a95b41b0dca8c308a33489dfdb28019e033110320414b4b16fad7d28c0f9f
Status: Image is up to date for redis:5
docker.io/library/redis:5
****** INIT
Preparing work directory /Users/alessandroercolani/tmp-iosdk-test for https://github.com/pagopa/io-sdk-javascript
Enumerating objects: 66, done.
Counting objects: 100% (66/66), done.
Compressing objects: 100% (46/46), done.
Total 66 (delta 26), reused 54 (delta 14), pack-reused 0
Done.
Wrote /Users/alessandroercolani/.iosdk
Wrote /Users/alessandroercolani/.wskprops
****** START
Deploying Redis...
skipping pull
TRAC[0000] < docker [run -d -p 6379:6379 --rm --name iosdk-redis --hostname redis library/redis:5] 
TRAC[0000] > 22e4f77b30cef13358e240f279c8a1cacdc454705421ce32fd8cf98a4921e3e2 
22e4f77b30cef13358e240f279c8a1cacdc454705421ce32fd8cf98a4921e3e2

Deploying Whisk...
skipping pull
TRAC[0000] < docker [inspect --format={{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} iosdk-redis] 
TRAC[0000] > 172.17.0.2                                 
172.17.0.2
TRAC[0000] < docker [run -d -p 3280:3280 --rm --name iosdk-openwhisk --hostname openwhisk -e CONTAINER_EXTRA_ENV=__OW_REDIS=172.17.0.2 -e CONFIG_FORCE_whisk_users_guest=fdb2f4af-4726-4408-88f8-c2eaf3d1b56a:C7xbu7OSbaBj15CVEoycPSUodNMp10U56qmOvzdgc2rtYZR4wSbu15nCGKkIA7aE -v //var/run/docker.sock:/var/run/docker.sock pagopa/iosdk-openwhisk:master] 
TRAC[0000] > c53d7f7f8862bccd50ce839457add7f8c3b5331bd20c38c775c3a344b4e6dae5 
c53d7f7f8862bccd50ce839457add7f8c3b5331bd20c38c775c3a344b4e6dae5
docker exec iosdk-openwhisk waitready
TRAC[0000] < docker [exec iosdk-openwhisk waitready]    
server: stopped, waiting...
server: stopped, waiting...
server: starting, waiting...
ready
Deploying IDE...
skipping pull
TRAC[0015] < docker [inspect --format={{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} iosdk-openwhisk] 
TRAC[0015] > 172.17.0.3                                 
172.17.0.3
TRAC[0015] < docker [run -d -p 3000:3000 --rm --name iosdk-theia --add-host=openwhisk:172.17.0.3 -v /Users/alessandroercolani/tmp-iosdk-test:/home/project pagopa/iosdk-theia:master] 
TRAC[0016] > 3b2d859279309699f602e70109dd7734e3d16842d7f3872cc0a39f0444903a76 
3b2d859279309699f602e70109dd7734e3d16842d7f3872cc0a39f0444903a76
Configuring Whisk
Configuring IDE
docker exec iosdk-theia wsk property set --apihost http://openwhisk:3280 --auth fdb2f4af-4726-4408-88f8-c2eaf3d1b56a:C7xbu7OSbaBj15CVEoycPSUodNMp10U56qmOvzdgc2rtYZR4wSbu15nCGKkIA7aE
TRAC[0016] < docker [exec iosdk-theia wsk property set --apihost http://openwhisk:3280 --auth fdb2f4af-4726-4408-88f8-c2eaf3d1b56a:C7xbu7OSbaBj15CVEoycPSUodNMp10U56qmOvzdgc2rtYZR4wSbu15nCGKkIA7aE] 
ok: whisk auth set. Run 'wsk property get --auth' to see the new value.
ok: whisk API host set to http://openwhisk:3280
****** BUILD
downloading libraries, please wait...
npm WARN checkPermissions Missing write access to /home/project
npm WARN io-sdk-javascript@0.1.0 No repository field.
npm WARN io-sdk-javascript@0.1.0 license should be a valid SPDX license expression

npm ERR! path /home/project
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/home/project'
npm ERR!  { [Error: EACCES: permission denied, access '/home/project']
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/home/project\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/project' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/theia/.npm/_logs/2020-05-01T20_53_59_462Z-debug.log
preparing archive, please wait...

zip error: Nothing to do! (try: zip -qr index.zip . -i node_modules)
	zip warning: index.zip not found or empty
zip I/O error: Permission denied
zip error: Could not create output file (index.zip)
error: Invalid argument(s). File 'index.zip' is not a valid file or it does not exist
Run 'wsk --help' for usage.
make[1]: *** [test] Error 2
make: *** [branch] Error 2

**Comment by sciabarracom** [comment]
fixed in 0.5.0
