### ISSUE TITLE
Dir not found

### ISSUE THREAD

**Issue by AndreaTironi1** [pagopa/io-sdk#45]
C:\Program Files>cd IOSDK

C:\Program Files\IOSDK>iosdk.exe init c:\Users\a.tironi\iosdk
work directory c:\Users\a.tironi\iosdk should be below your home directory C:\Users\a.tironi;
this is required to be accessible by Docker

C:\Program Files\IOSDK>dir c:\Users\a.tironiiosdk
 Volume in drive C is Windows
 Volume Serial Number is C04D-A612

 Directory of c:\Users

File Not Found

C:\Program Files\IOSDK>

**Comment by sciabarracom** [comment]
iosdk shold be in the path so no need to change directory
you may need to open a new terminal
in the example a slash is missing
