### ISSUE TITLE
exit status 1

### ISSUE THREAD

**Issue by AndreaTironi1** [pagopa/io-sdk#46]
Docker for windows desktop install with default parameters

C:\Users\a.tironi>cd iosdk

C:\Users\a.tironi\iosdk>"c:\Program Files\IOSDK\iosdk.exe" start
**exit status 1**

C:\Users\a.tironi\iosdk>docker

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default
                           "C:\\Users\\a.tironi\\.docker")
  -c, --context string     Name of the context to use to connect to the
                           daemon (overrides DOCKER_HOST env var and
                           default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level
                           ("debug"|"info"|"warn"|"error"|"fatal")
                           (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default
                           "C:\\Users\\a.tironi\\.docker\\ca.pem")
      --tlscert string     Path to TLS certificate file (default
                           "C:\\Users\\a.tironi\\.docker\\cert.pem")
      --tlskey string      Path to TLS key file (default
                           "C:\\Users\\a.tironi\\.docker\\key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  builder     Manage builds
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  deploy      Deploy a new stack or update an existing stack
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

C:\Users\a.tironi\iosdk>

**Comment by sciabarra** [comment]
Per favore dai iosdk -v start e riporta l'output

**Comment by AndreaTironi1** [comment]
C:\Users\a.tironi\iosdk>iosdk -v start
time="2020-05-07T11:50:46+02:00" level=trace msg="< docker [version --format {{.Server.Version}}]\n"
time="2020-05-07T11:50:46+02:00" level=trace msg="> ERROR: exit status 1"
exit status 1

**Comment by AndreaTironi1** [comment]
C:\Users\a.tironi\iosdk>dir
 Volume in drive C is Windows
 Volume Serial Number is C04D-A612

 Directory of C:\Users\a.tironi\iosdk

06/05/2020  13:01    <DIR>          .
06/05/2020  13:01    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  33.862.967.296 bytes free

C:\Users\a.tironi\iosdk>dir ..\.iosdk
 Volume in drive C is Windows
 Volume Serial Number is C04D-A612

 Directory of C:\Users\a.tironi

06/05/2020  16:32               381 .iosdk
               1 File(s)            381 bytes
               0 Dir(s)  33.863.024.640 bytes free

C:\Users\a.tironi\iosdk>iosdk -v start
time="2020-05-07T11:50:46+02:00" level=trace msg="< docker [version --format {{.Server.Version}}]\n"
time="2020-05-07T11:50:46+02:00" level=trace msg="> ERROR: exit status 1"
exit status 1

C:\Users\a.tironi\iosdk>

**Comment by AndreaTironi1** [comment]
C:\Users\a.tironi\iosdk>docker --version
Docker version 19.03.8, build afacb8b

**Comment by sciabarra** [comment]
interessante potresti dirmi cosa scrive `docker version` ? 
E cosa scrive `docker version --format "{{.Server.Version}}"

**Comment by AndreaTironi1** [comment]
C:\Users\a.tironi\iosdk>docker version --format "{{.Server.Version}}"

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version:
open //./pipe/docker_engine: The system cannot find the file specified. In
the default daemon configuration on Windows, the docker client must be run
elevated to connect. This error may also indicate that the docker daemon is
not running.

Need to start docker? Sorry, it is my first installation.

Il giorno gio 7 mag 2020 alle ore 12:39 Michele Sciabarra <
notifications@github.com> ha scritto:

**Comment by sciabarra** [comment]
LOL yes :) Actually this problem already happened I will open an issue to to a preflight check about docker being up and ruinning.
