### ISSUE TITLE
"Michele Sciabarra" page not found

### ISSUE THREAD

**Issue by AndreaTironi1** [pagopa/io-sdk#49]
"Michele Sciabarra" page not found clicking on "Michele Sciabarra" link on upper right menù.

**Comment by mdigirolamo** [comment]
This is a part of template, if you want we can remove it.

**Comment by AndreaTironi1** [comment]
Keep ti simple, if needed insert a 200 link, else remove it :)

Il giorno lun 11 mag 2020 alle ore 15:59 Mirella Di Girolamo <
notifications@github.com> ha scritto:

**Comment by sciabarracom** [comment]
remoevd
