### ISSUE TITLE
data.xls / test.xls

### ISSUE THREAD

**Issue by AndreaTironi1** [pagopa/io-sdk#62]
I insert my CF in data.xls.
When i click on import in"import messages" page,
it shows test CF, not mine.
I insert my CF in test.xls.
When i click on import in"import messages" page,
it shows test CF, not mine.

Why?

Andrea

**Comment by sciabarracom** [comment]
Can you provide a screenshot?

**Comment by sciabarracom** [comment]
cannnot replicate - reopen if you can provide a screenshot.
