### ISSUE TITLE
Send to production: no parameter 'fiscal_code

### ISSUE THREAD

**Issue by AndreaTironi1** [pagopa/io-sdk#64]
I click on send messages.
I click on first message.
I click sent after i choose production.
(before that i insert an io-apicode).

"{"error":"no parameter 'fiscal_code'"}"

Andrea

**Comment by sciabarracom** [comment]
looks like for some reasons the fiscal code was not imported, please import the message, then click on the link of the message and check all the fields are filed

**Comment by sciabarracom** [comment]
fixed
