### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by AndreaTironi1** [pagopa/io-sdk#65]
How can I use cache?

Cache Data
Key:
message:ISPXNB32R82Y766F

Value:
{
  "message:ISPXNB32R82Y766F": {
    "amount": 0,
    "due_date": 44197,
    "fiscal_code": "ISPXNB32R82Y766F",
    "invalid_after_due_date": false,
    "markdown": "# Welcome, Giovanni Rossi\\\\nYour fiscal code is ISPXNB32R82Y766F\\\\nI hope you will enjoy IO.",
    "notice_number": 1,
    "subject": "Welcome to IO, Giovanni"
  }
}

**Comment by sciabarra** [comment]
just shown for debugging purposes
