### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by AndreaTironi1** [pagopa/io-sdk#72]
I like a dahsboard

![image](https://user-images.githubusercontent.com/29781117/81475735-4733dc80-920e-11ea-932e-3b56ce5814ef.png)

with "Messaggi inviati totali", "Messaggi con errori", "Processi batch riusciti / esito ultimo processo batch"

**Comment by sciabarracom** [comment]
moved to https://wiki.noiopen.it/wiki/IoGatewayBacklog
