### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by AndreaTironi1** [pagopa/io-sdk#73]
./build.sh started
I can import data.xls.
I go to send messages.
I see only one message, not two.
I try to send:
message:TRN********** ERROR: Post https://api.cd.italia.it/api/v1/messages: dial tcp: lookup api.cd.italia.it on 192.168.65.1:53: no such host

Andrea

**Comment by sciabarracom** [comment]
Confirmed end point changed

**Comment by sciabarracom** [comment]
FIxed endpoint in master
