### ISSUE TITLE
Errror following DEVEL.md util.go:14:2: module github.com/pagopa/go-input@latest found (v0.0.0-20200505145315-93dcdc111b12), but does not contain package github.com/pagopa/go-input

### ISSUE THREAD

**Issue by giux78** [pagopa/io-sdk#75]
`util.go:14:2: module github.com/pagopa/go-input@latest found (v0.0.0-20200505145315-93dcdc111b12), but does not contain package github.com/pagopa/go-input `

I have the error above while trying to setup the development environment.

**Comment by sciabarracom** [comment]
which version of go you have? use `go version`

**Comment by sciabarracom** [comment]
also try this:
```
mkdir /tmp/go
cd iosdk
GOPATH=/tmp/go go build
```

**Comment by giux78** [comment]
go version go1.14.2 darwin/amd64

**Comment by sciabarracom** [comment]
Solved by cleaning cache
