### ISSUE TITLE
iosdk app-dir

### ISSUE THREAD

**Issue by tkdudine** [pagopa/io-sdk#87]
I have an issue with iosdk installation on a wondows10 home ed with a docker machine deplyed ok a linux vm with virtualbox. 
To make iosdk installable in this environment without an error response from daemon: invalid mode: /root/project, it is necessary to use linux notation in the app-dir path both for app-dir and project dir. 
A working example can be this: //c/Users/{user}/project://home/project

Some other information about my system:

win10 home 1903
virtualbox 6.0
Docker version 19.03.3, build 2355349d- installed on a linux vm running on virtualbox

Tks!

**Comment by sciabarracom** [comment]
The problem is that this happens apparently when you use Docker Toolbox.
Unfortunately, the path that works with docker desktop DOES NOT with docker toolbox.
I need a way to detect which one is running.
What is the output of your docker info?
Most notably the OperatingSystem.
Mine is:
```
Operating System: Docker Desktop
OSType: linux
````

**Comment by tkdudine** [comment]
This is the oputput of docker info (it is a test installation!)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.130-boot2docker
 Operating System: Boot2Docker 19.03.12 (TCL 10.1)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.852GiB
 Name: default
 ID: FD2M:WIUX:5VQJ:ZP45:IVFO:3PUV:SZSL:OKZX:SP2O:XJMY:BTRG:446Y
 Docker Root Dir: /mnt/sda1/var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=virtualbox
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by sciabarracom** [comment]
Fixed
